# TCL File Generated by Component Editor 13.0sp1
# Mon May 04 23:48:33 BST 2020
# DO NOT MODIFY


# 
# count_leading_ones "count_leading_ones" v1.0
# Unfortunate George 2020.05.04.23:48:33
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module count_leading_ones
# 
set_module_property DESCRIPTION ""
set_module_property NAME count_leading_ones
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Unfortunate George"
set_module_property DISPLAY_NAME count_leading_ones
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL count_leading_ones
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file count_leading_ones.v VERILOG PATH "../../../../../../Google Drive/Liverpool/elec473/assign4/count_leading_ones.v" TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL count_leading_ones
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file count_leading_ones.v VERILOG PATH "../../../../../../Google Drive/Liverpool/elec473/assign4/count_leading_ones.v"


# 
# parameters
# 
add_parameter size INTEGER 32
set_parameter_property size DEFAULT_VALUE 32
set_parameter_property size DISPLAY_NAME size
set_parameter_property size TYPE INTEGER
set_parameter_property size UNITS None
set_parameter_property size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave inA dataa Input size
add_interface_port nios_custom_instruction_slave rslt result Output size

