# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab3_simple/lab3_simple.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple || ORIG_REF_NAME==lab3_simple} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_processing_system7_0_0/lab3_simple_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_processing_system7_0_0 || ORIG_REF_NAME==lab3_simple_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab3_simple_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_ps7_0_axi_periph_1_0/lab3_simple_ps7_0_axi_periph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_ps7_0_axi_periph_1_0 || ORIG_REF_NAME==lab3_simple_ps7_0_axi_periph_1_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_super_multiplication_0_0_1/lab3_simple_super_multiplication_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_super_multiplication_0_0 || ORIG_REF_NAME==lab3_simple_super_multiplication_0_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_auto_pc_0/lab3_simple_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_auto_pc_0 || ORIG_REF_NAME==lab3_simple_auto_pc_0} -quiet] -quiet

# XDC: bd/lab3_simple/lab3_simple_ooc.xdc
