# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_processing_system7_0_0/lab3_simple_processing_system7_0_0.xci
# IP: The module: 'lab3_simple_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_processing_system7_0_0/lab3_simple_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_processing_system7_0_0/lab3_simple_processing_system7_0_0.xci
# IP: The module: 'lab3_simple_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_processing_system7_0_0/lab3_simple_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
