# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0.xci
# IP: The module: 'lab3_simple_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0.xci
# IP: The module: 'lab3_simple_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/geoka/Documents/GitHub/uni-projects/lab4/lab4_matrix_multiplicatio/lab4_matrix_multiplicatio.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_simple_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
