# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.cache/wt [current_project]
set_property parent.project_path /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/gkmikros/Dropbox/CE435/Lab3/ip_repo_gray/Gray_counter_ip_1.0
  /home/gkmikros/ip_repo/led_ip_1.0
} [current_project]
set_property ip_output_repo /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/hdl/lab3_simple_wrapper.v
add_files /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/lab3_simple.bd
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_processing_system7_0_0/lab3_simple_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_axi_gpio_0_0/lab3_simple_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_axi_gpio_0_0/lab3_simple_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_axi_gpio_0_0/lab3_simple_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_0/lab3_simple_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_axi_gpio_0_1/lab3_simple_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_axi_gpio_0_1/lab3_simple_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_axi_gpio_0_1/lab3_simple_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_xbar_0/lab3_simple_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/ip/lab3_simple_auto_pc_0/lab3_simple_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/lab3_simple_ooc.xdc]
set_property is_locked true [get_files /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/sources_1/bd/lab3_simple/lab3_simple.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/constrs_1/imports/new/custom_ip_cons.xdc
set_property used_in_implementation false [get_files /home/gkmikros/Dropbox/CE435/Lab3/lab3_graycounter/lab3_graycounter.srcs/constrs_1/imports/new/custom_ip_cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lab3_simple_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef lab3_simple_wrapper.dcp

catch { report_utilization -file lab3_simple_wrapper_utilization_synth.rpt -pb lab3_simple_wrapper_utilization_synth.pb }
