# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/custom_ip_cons.xdc

# Block Designs: bd/lab3_simple/lab3_simple.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple || ORIG_REF_NAME==lab3_simple} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_processing_system7_0_1/lab3_simple_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_processing_system7_0_1 || ORIG_REF_NAME==lab3_simple_processing_system7_0_1} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_xlconcat_0_0/lab3_simple_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_xlconcat_0_0 || ORIG_REF_NAME==lab3_simple_xlconcat_0_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_axi_dma_0/lab3_simple_axi_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_axi_dma_0 || ORIG_REF_NAME==lab3_simple_axi_dma_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_axi_mem_intercon_0/lab3_simple_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_axi_mem_intercon_0 || ORIG_REF_NAME==lab3_simple_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_rst_ps7_0_100M_1/lab3_simple_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_rst_ps7_0_100M_1 || ORIG_REF_NAME==lab3_simple_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_ps7_0_axi_periph_0/lab3_simple_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab3_simple_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_xbar_4/lab3_simple_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_xbar_4 || ORIG_REF_NAME==lab3_simple_xbar_4} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_xbar_5/lab3_simple_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_xbar_5 || ORIG_REF_NAME==lab3_simple_xbar_5} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_auto_us_0/lab3_simple_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_auto_us_0 || ORIG_REF_NAME==lab3_simple_auto_us_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_auto_us_1/lab3_simple_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_auto_us_1 || ORIG_REF_NAME==lab3_simple_auto_us_1} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_auto_pc_0/lab3_simple_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_auto_pc_0 || ORIG_REF_NAME==lab3_simple_auto_pc_0} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_auto_pc_1/lab3_simple_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_auto_pc_1 || ORIG_REF_NAME==lab3_simple_auto_pc_1} -quiet] -quiet

# IP: bd/lab3_simple/ip/lab3_simple_sobel_filter_1_1/lab3_simple_sobel_filter_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab3_simple_sobel_filter_1_1 || ORIG_REF_NAME==lab3_simple_sobel_filter_1_1} -quiet] -quiet

# XDC: bd/lab3_simple/lab3_simple_ooc.xdc
